name: raid-callouts
channels:
  - defaults
dependencies:
  - astroid=3.2.4
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - charset-normalizer=2.0.4
  - dill=0.3.8
  - idna=3.7
  - isort=5.13.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - mccabe=0.7.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.11.5
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tomlkit=0.13.2
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.1
      - attrs==23.2.0
      - certifi==2024.12.14
      - discord-py==2.4.0
      - frozenlist==1.4.1
      - iniconfig==2.0.0
      - multidict==6.0.5
      - packaging==24.1
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - propcache==0.2.1
      - psycopg2-binary==2.9.9
      - pylint==3.2.6
      - pytest==8.2.2
      - requests>=2.32.4
      - setuptools>=78.1.1
      - urllib3==2.5.0
      - yarl==1.18.3
