name: "Test Helper Module"

on:
    push:
        branches:
            - gabby-dev
            - josh-dev

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.11.5]
                
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Set up conda /w python version ${{ matrix.python-version }}
              uses: conda-incubator/setup-miniconda@v3.0.2
              with:
                  auto-update-conda: true
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              shell: bash -l {0}
              run: |
                  conda env create --file environment.yml -n test-helper-module
                  conda init
                  conda activate test-helper-module
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: add database.ini
              shell: bash -l {0}
              run: |
                    cd $GITHUB_WORKSPACE/
                    touch database.ini
                    echo "${{ secrets.DATABASE_INI }}" >> xiv-database.ini

            - name: Run tests
              shell: bash -l {0}
              run: |
                cd $GITHUB_WORKSPACE
                conda activate test-helper-module
                python -m pytest ./src/py/db_helper_tests.py
