name: "Test Helper Module"

on:
    push:
        branches:
            - gabby-dev
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.11.5]
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Set up conda /w python version ${{ matrix.python-version }}
              uses: conda-incubator/setup-miniconda@v3.0.2
              with:
                  auto-update-conda: true
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              shell: bash -l {0}
              run: |
                  conda env create -f environment.yml -n test-helper-module
                  conda init
                  conda activate test-helper-module
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run tests
              shell: bash -l {0}
              run: |
                conda activate test-helper-module
                python -m pytest src/py/db-helper-tests.py